archives:
  - id: archive
    name_template: '{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}'
before:
  hooks:
    - make build_provider
builds:
  - binary: pulumi-resource-azure-quickstart-acr-geo-replication
    dir: provider
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
    goos:
      - darwin
      - windows
      - linux
    ldflags:
      - -X github.com/pulumi/pulumi-azure-quickstart-acr-geo-replication/provider/pkg/version.Version={{.Tag }}
    main: ./cmd/pulumi-resource-azure-quickstart-acr-geo-replication/
changelog:
  skip: true
release:
  disable: false
  prerelease: auto
snapshot:
  name_template: '{{ .Tag }}-SNAPSHOT'
